backend:
  name: github
  repo: vaspadi/nuxt-netlify
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/img/uploads
public_folder: uploads

collections:
  - name: 'vacancies'
    label: 'Вакансии'
    folder: 'content/vacancies'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    filter:
      field: archive
      value: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'hr-manager' }
      - { label: 'Картинка', name: 'img', widget: 'image', media_folder: /assets/img/vacancies }
      - { label: 'Заголовок вакансии', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Добавить в архив', name: 'archive', widget: 'boolean' }

  - name: vacancies-archive
    label: Вакансии - архив
    folder: content/vacancies
    format: frontmatter
    create: false
    editor:
      preview: false
    filter:
      field: archive
      value: true
    fields:
      - label: Добавить в архив
        name: archive
        widget: boolean

  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'choose-company' }
      - { label: 'Картинка', name: 'img', widget: 'image', media_folder: /assets/img/news }
      - { label: 'Заголовок новости', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Добавить на главную страницу', name: indexPage, widget: boolean, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: index-page
    label: 'Страница: Главная'
    files:
      - label: Стать инвестором
        name: becomeInvestor
        file: content/index-page/becomeInvestor.json
        editor:
          preview: false
        fields:
          - label: Стать инвестором
            name: becomeInvestor
            widget: object
            fields:
              - label: Заголовок
                name: title
                widget: string

              - label: Текст
                name: text
                widget: text

              - label: Идентификатор видео с youtube
                name: video
                widget: string
                hint: youtube.com/watch?v= >>>> cQDeUcGxy48 <<<<

  - name: investor-page
    label: 'Страница: Стать инвестором'
    files:
      - label: Выбор инвестиций
        name: investmentsSelection
        file: content/investor-page/investmentsSelection.json
        editor:
          preview: false
        fields:
          - label: Типы инвестиций
            name: investments
            widget: list
            minimize_collapsed: true
            fields:
              - label: Объем инвестиций от
                name: price
                widget: number
                min: 0
                hint: рублей

              - label: Доход от
                name: profit
                widget: number
                min: 0
                hint: руб/мес

              - label: Доходность на вложенный капиталл
                name: profitCapital
                widget: number
                min: 0
                hint: процентов

          - label: Классы машин
            name: carClasses
            widget: list
            minimize_collapsed: true
            fields:
              - label: Заголовок
                name: name
                widget: string

              - label: slug
                name: value
                widget: string

          - label: Машины
            name: cars
            widget: list
            minimize_collapsed: true
            fields:
              - label: Название
                name: title
                widget: string

              - label: Картинка
                name: img
                widget: image
                media_folder: /assets/img/cars

              - label: Класс машины
                name: type
                widget: relation
                collection: investor-page
                file: investmentsSelection
                value_field: carClasses.*.value
                search_fields: [ carClasses.*.name, carClasses.*.value ]
                display_fields: [ carClasses.*.name ]

      - label: Модели инвестиций
        name: investmentsModels
        file: content/investor-page/investmentsModels.json
        editor:
          preview: false
        fields:
          - label: Табы переключения таблиц
            name: investmentTypes
            widget: object
            collapsed: true
            fields:
              - label: Заголовок всех табов
                name: title
                widget: string

              - label: Табы
                name: buttons
                widget: list
                fields:
                  - label: Заговок
                    name: title
                    widget: string

                  - label: slug
                    name: type
                    widget: string

                  - label: Картинка для таба
                    name: img
                    widget: image
                    media_folder: /assets/img/cars

          - label: "Таблицы"
            name: "investmentsModels"
            widget: "list"
            fields:
            - label: 'Название таблицы'
              name: 'title'
              widget: 'string'

            - label: Кнопка таба
              name: name
              widget: relation
              collection: investor-page
              file: investmentsModels
              value_field: investmentTypes.buttons.*.type
              search_fields: [investmentTypes.buttons.*.title, investmentTypes.buttons.*.type]
              display_fields: [investmentTypes.buttons.*.title]

            - label: Строка
              name: table
              widget: list
              minimize_collapsed: true
              fields:
                - label: Описание
                  name: title
                  widget: string

                - label: Цена
                  name: num
                  widget: number

                - label: Выделить
                  name: selected
                  widget: boolean
                  required: false

      - label: Истории инвесторов
        name: investors
        file: content/investor-page/investors.json
        editor:
          preview: false
        fields:
          - label: Истории инвесторов
            name: investors
            widget: list
            fields:
              - label: ФИО
                name: name
                widget: string

              - label: Сумма инвистиций
                name: investments
                widget: number
                hint: рублей

              - label: Количество доходных машин
                name: cars
                widget: number

              - label: Прибыль в месяц
                name: income
                widget: number
                hint: рублей

              - label: Идентификатор видео с youtube
                name: video
                widget: string
                hint: youtube.com/watch?v= >>>> cQDeUcGxy48 <<<<

      - label: Видеоряд
        name: videoGallery
        file: content/investor-page/videoGallery.json
        editor:
          preview: false
        fields:
          - label: Видеоряд
            name: videos
            widget: list
            fields:
              - label: Заголовок
                name: name
                widget: string
                required: false

              - label: Идентификатор видео с youtube
                name: id
                widget: string
                hint: youtube.com/watch?v= >>>> cQDeUcGxy48 <<<<

  - name: documents-page
    label: 'Страница: Документы'
    files:
      - label: Документы
        name: documents
        file: content/documents-page/documents.json
        editor:
          preview: false
        fields:
          - label: Группы документов
            name: documentsGroup
            widget: list
            fields:
              - label: Заголовок на сайте
                name: name
                widget: string

              - label: Документ
                name: path
                widget: file
                media_folder: /static/documents

              - label: Инвесторам
                name: investors
                widget: boolean
                required: false

              - label: Водителям
                name: drivers
                widget: boolean
                required: false

  - name: structure-page
    label: 'Страница: Структура'
    files:
      - label: Сотрудники
        name: employees
        file: content/structure-page/employees.json
        editor:
          preview: false
        fields:
          - label: Группы сотрудников
            name: employeesGroups
            widget: list
            minimize_collapsed: true
            fields:
              - label: Название группы
                name: title
                widget: string

              - label: slug
                name: name
                widget: string

          - label: Сотрудники
            name: employees
            widget: list
            fields:
              - label: Имя
                name: name
                widget: string

              - label: Должность
                name: position
                widget: string

              - label: Фотография
                name: photo
                widget: image
                media_folder: /assets/img/employees

              - label: Группа
                name: group
                widget: relation
                collection: structure-page
                file: employees
                value_field: employeesGroups.*.name
                search_fields: [ employeesGroups.*.title, employeesGroups.*.name ]
                display_fields: [ employeesGroups.*.title ]

  - name: contacts-page
    label: 'Страница: Контакты'
    files:
      - label: Контакты
        name: contacts
        file: content/contacts-page/contacts.json
        editor:
          preview: false
        fields:
          - label: Города
            name: contactsCities
            widget: list
            minimize_collapsed: true
            fields:
              - label: Название города
                name: title
                widget: string

              - label: slug
                name: name
                widget: string

          - label: Контакты
            name: contacts
            widget: list
            fields:
              - label: Город
                name: city
                widget: relation
                collection: contacts-page
                file: contacts
                value_field: contactsCities.*.name
                search_fields: [ contactsCities.*.title, contactsCities.*.name ]
                display_fields: [ contactsCities.*.title ]

              - label: Телефон
                name: telephones
                widget: list
                fields:
                  - label: Описание
                    name: telDescription
                    widget: string
                    hint: '+7 (8112) 29-60-01'

                  - label: Ссылка
                    name: tel
                    widget: string
                    hint: '+78112296001'

              - label: Почта
                name: email
                widget: string

              - label: Адрес
                name: addresses
                fields:
                  - label: Адрес
                    name: address
                    widget: string
