backend:
  name: github
  repo: vaspadi/nuxt-netlify
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/img/uploads
public_folder: uploads

collections:
  - name: 'vacancies'
    label: 'Вакансии'
    folder: 'content/vacancies'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'hr-manager' }
      - { label: 'Картинка', name: 'img', widget: 'image', media_folder: /assets/img/vacancies }
      - { label: 'Заголовок вакансии', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'choose-company' }
      - { label: 'Картинка', name: 'img', widget: 'image', media_folder: /assets/img/news }
      - { label: 'Заголовок новости', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'investor-page'
    label: 'Страница: Стать инвестором'
    files:
      - label: Выбор инвестиций
        name: investmentsSelection
        file: content/investor-page/investmentsSelection.json
        editor:
          preview: false
        fields:
          - label: Типы инвестиций
            name: investments
            widget: list
            minimize_collapsed: true
            fields:
              - label: Объем инвестиций от
                name: price
                widget: number
                min: 0
                hint: рублей

              - label: Доход от
                name: profit
                widget: number
                min: 0
                hint: руб/мес

              - label: Доходность на вложенный капиталл
                name: profitCapital
                widget: number
                min: 0
                hint: процентов

          - label: Классы машин
            name: carClasses
            widget: list
            minimize_collapsed: true
            fields:
              - label: Заголовок
                name: name
                widget: string

              - label: slug
                name: value
                widget: string

          - label: Машины
            name: cars
            widget: list
            minimize_collapsed: true
            fields:
              - label: Название
                name: title
                widget: string

              - label: Картинка
                name: img
                widget: image
                media_folder: /assets/img/cars

              - label: Класс машины
                name: type
                widget: relation
                collection: investor-page
                file: investmentsSelection
                value_field: carClasses.*.value
                search_fields: [ carClasses.*.name, carClasses.*.value ]
                display_fields: [ carClasses.*.name ]

      - label: Модели инвестиций
        name: investmentsModels
        file: content/investor-page/investmentsModels.json
        editor:
          preview: false
        fields:
          - label: Табы переключения таблиц
            name: investmentTypes
            widget: object
            collapsed: true
            fields:
              - label: Заголовок всех табов
                name: title
                widget: string

              - label: Табы
                name: buttons
                widget: list
                fields:
                  - label: Заговок
                    name: title
                    widget: string

                  - label: slug
                    name: type
                    widget: string

                  - label: Картинка для таба
                    name: img
                    widget: image
                    media_folder: /assets/img/cars

          - label: "Таблицы"
            name: "investmentsModels"
            widget: "list"
            fields:
            - label: 'Название таблицы'
              name: 'title'
              widget: 'string'

            - label: Кнопка таба
              name: name
              widget: relation
              collection: investor-page
              file: investmentsModels
              value_field: investmentTypes.buttons.*.type
              search_fields: [investmentTypes.buttons.*.title, investmentTypes.buttons.*.type]
              display_fields: [investmentTypes.buttons.*.title]

            - label: Строка
              name: table
              widget: list
              minimize_collapsed: true
              fields:
                - label: Описание
                  name: title
                  widget: string

                - label: Цена
                  name: num
                  widget: number

                - label: Выделить
                  name: selected
                  widget: boolean
                  required: false

      - label: Истории инвесторов
        name: investors
        file: content/investor-page/investors.json
        editor:
          preview: false
        fields:
          - label: Истории инвесторов
            name: investors
            widget: list
            fields:
              - label: ФИО
                name: name
                widget: string

              - label: Сумма инвистиций
                name: investments
                widget: number
                hint: рублей

              - label: Количество доходных машин
                name: cars
                widget: number

              - label: Прибыль в месяц
                name: income
                widget: number
                hint: рублей

              - label: Идентификатор видео с youtube
                name: video
                widget: string
                hint: youtube.com/watch?v= >>>> cQDeUcGxy48 <<<<

      - label: Видеоряд
        name: videoGallery
        file: content/investor-page/videoGallery.json
        editor:
          preview: false
        fields:
          - label: Видеоряд
            name: videos
            widget: list
            fields:
              - label: Заголовок
                name: name
                widget: string
                required: false

              - label: Идентификатор видео с youtube
                name: id
                widget: string
                hint: youtube.com/watch?v= >>>> cQDeUcGxy48 <<<<
