backend:
  name: github
  repo: vaspadi/nuxt-netlify
  branch: master # Branch to update (optional; defaults to master)

media_folder: assets/img/uploads
public_folder: uploads

collections:
  - name: 'vacancies'
    label: 'Вакансии'
    folder: 'content/vacancies'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'hr-manager' }
      - { label: 'Картинка', name: 'img', widget: 'image' }
      - { label: 'Заголовок вакансии', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'news'
    label: 'Новости'
    folder: 'content/news'
    format: 'frontmatter'
    create: true
    slug: '{{fields.slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок страницы', name: 'metaTitle', widget: 'string' }
      - { label: 'Название файла', name: 'slug', widget: 'string', default: 'choose-company' }
      - { label: 'Картинка', name: 'img', widget: 'image' }
      - { label: 'Заголовок новости', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'investor-page'
    label: 'Страница: Стать инвестором'
    files:
      - label: Выбор инвестиций
        name: investmentsSelection
        file: content/investor-page/investmentsSelection.json
        editor:
          preview: false
        fields:
          - label: Типы инвестиций
            name: investments
            widget: list
            fields:
              - label: Объем инвестиций от
                name: price
                widget: number
                min: 0
                hint: рублей
              - label: Доход от
                name: profit
                widget: number
                min: 0
                hint: руб/мес
              - label: Доходность на вложенный капиталл
                name: profitCapital
                widget: number
                min: 0
                hint: процентов

      - label: Модели инвестиций
        name: investmentsModels
        file: content/investor-page/investmentsModels.json
        editor:
          preview: false
        fields:
          - label: Табы переключения таблиц
            name: investmentTypes
            widget: object
            collapsed: true
            fields:
              - label: Заголовок всех табов
                name: title
                widget: string
              - label: Табы
                name: buttons
                widget: list
                fields:
                  - label: Заговок
                    name: title
                    widget: string
                  - label: slug
                    name: type
                    widget: string
                  - label: Картинка для таба
                    name: img
                    widget: image

          - label: "Таблицы"
            name: "investmentsModels"
            widget: "list"
            fields:
            - label: 'Название таблицы'
              name: 'title'
              widget: 'string'
            - label: Кнопка таба
              name: name
              widget: relation
              collection: investor-page
              file: investmentsModels
              value_field: investmentTypes.buttons.*.type
              search_fields: [investmentTypes.buttons.*.title, investmentTypes.buttons.*.type]
              display_fields: [investmentTypes.buttons.*.title]
            - label: Строка
              name: table
              widget: list
              minimize_collapsed: true
              fields:
                - label: Описание
                  name: title
                  widget: string
                - label: Цена
                  name: num
                  widget: number
                - label: Выделить
                  name: selected
                  widget: boolean
                  required: false

